[2022-04-20 00:20:45,869] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.download_dataset_task scheduled__2022-04-19T00:00:00+00:00 [queued]>
[2022-04-20 00:20:45,874] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.download_dataset_task scheduled__2022-04-19T00:00:00+00:00 [queued]>
[2022-04-20 00:20:45,874] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-20 00:20:45,874] {taskinstance.py:1250} INFO - Starting attempt 1 of 2
[2022-04-20 00:20:45,875] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-20 00:20:45,882] {taskinstance.py:1270} INFO - Executing <Task(BashOperator): download_dataset_task> on 2022-04-19 00:00:00+00:00
[2022-04-20 00:20:45,885] {standard_task_runner.py:52} INFO - Started process 1869 to run task
[2022-04-20 00:20:45,886] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'download_dataset_task', 'scheduled__2022-04-19T00:00:00+00:00', '--job-id', '346', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmp4gtjvr6v', '--error-file', '/tmp/tmpi9kmvuji']
[2022-04-20 00:20:45,887] {standard_task_runner.py:80} INFO - Job 346: Subtask download_dataset_task
[2022-04-20 00:20:45,912] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcs_dag.download_dataset_task scheduled__2022-04-19T00:00:00+00:00 [running]> on host 1b91fda6947c
[2022-04-20 00:20:45,937] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2022-04-19T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-04-19T00:00:00+00:00
[2022-04-20 00:20:45,938] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-04-20 00:20:45,938] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2021-01.csv > /opt/***/yellow_tripdata_2021-01.csv']
[2022-04-20 00:20:45,944] {subprocess.py:85} INFO - Output:
[2022-04-20 00:20:55,967] {local_task_job.py:212} WARNING - State of this instance has been externally set to removed. Terminating instance.
[2022-04-20 00:20:55,968] {process_utils.py:124} INFO - Sending Signals.SIGTERM to group 1869. PIDs of all processes in the group: [1870, 1871, 1869]
[2022-04-20 00:20:55,968] {process_utils.py:75} INFO - Sending the signal Signals.SIGTERM to group 1869
[2022-04-20 00:20:55,968] {taskinstance.py:1430} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-04-20 00:20:55,969] {subprocess.py:99} INFO - Sending SIGTERM signal to process group
[2022-04-20 00:20:55,969] {process_utils.py:70} INFO - Process psutil.Process(pid=1871, status='terminated', started='00:20:45') (1871) terminated with exit code None
[2022-04-20 00:20:55,975] {taskinstance.py:1774} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 182, in execute
    cwd=self.cwd,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/subprocess.py", line 87, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b''):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1432, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2022-04-20 00:20:55,979] {taskinstance.py:1288} INFO - Marking task as FAILED. dag_id=data_ingestion_gcs_dag, task_id=download_dataset_task, execution_date=20220419T000000, start_date=20220420T002045, end_date=20220420T002055
[2022-04-20 00:20:55,988] {standard_task_runner.py:98} ERROR - Failed to execute job 346 for task download_dataset_task (Task received SIGTERM signal; 1869)
[2022-04-20 00:20:55,996] {process_utils.py:70} INFO - Process psutil.Process(pid=1869, status='terminated', exitcode=1, started='00:20:45') (1869) terminated with exit code 1
[2022-04-20 00:20:55,996] {process_utils.py:70} INFO - Process psutil.Process(pid=1870, status='terminated', started='00:20:45') (1870) terminated with exit code None
