[2022-04-20 20:56:58,617] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: green_taxi_data_v4.download_dataset_task scheduled__2022-03-02T07:00:00+00:00 [queued]>
[2022-04-20 20:56:58,622] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: green_taxi_data_v4.download_dataset_task scheduled__2022-03-02T07:00:00+00:00 [queued]>
[2022-04-20 20:56:58,622] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-20 20:56:58,622] {taskinstance.py:1250} INFO - Starting attempt 1 of 2
[2022-04-20 20:56:58,622] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-20 20:56:58,629] {taskinstance.py:1270} INFO - Executing <Task(BashOperator): download_dataset_task> on 2022-03-02 07:00:00+00:00
[2022-04-20 20:56:58,631] {standard_task_runner.py:52} INFO - Started process 2200 to run task
[2022-04-20 20:56:58,632] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'green_taxi_data_v4', 'download_dataset_task', 'scheduled__2022-03-02T07:00:00+00:00', '--job-id', '759', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag_v02.py', '--cfg-path', '/tmp/tmppxu8bn1_', '--error-file', '/tmp/tmp_5pmtyo0']
[2022-04-20 20:56:58,632] {standard_task_runner.py:80} INFO - Job 759: Subtask download_dataset_task
[2022-04-20 20:56:58,656] {logging_mixin.py:109} INFO - Running <TaskInstance: green_taxi_data_v4.download_dataset_task scheduled__2022-03-02T07:00:00+00:00 [running]> on host 5a0aea9ec23a
[2022-04-20 20:56:58,673] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:156: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-04-20 20:56:58,686] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=green_taxi_data_v4
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2022-03-02T07:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-02T07:00:00+00:00
[2022-04-20 20:56:58,687] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-04-20 20:56:58,687] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSLf https://s3.amazonaws.com/nyc-tlc/trip+data/green_tripdata_2022-03.csv > /opt/***/green_tripdata_2022-03.csv']
[2022-04-20 20:56:58,691] {subprocess.py:85} INFO - Output:
[2022-04-20 20:56:58,893] {subprocess.py:89} INFO - curl: (22) The requested URL returned error: 404 Not Found
[2022-04-20 20:56:58,894] {subprocess.py:93} INFO - Command exited with return code 22
[2022-04-20 20:56:58,900] {taskinstance.py:1774} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 22.
[2022-04-20 20:56:58,903] {taskinstance.py:1288} INFO - Marking task as UP_FOR_RETRY. dag_id=green_taxi_data_v4, task_id=download_dataset_task, execution_date=20220302T070000, start_date=20220420T205658, end_date=20220420T205658
[2022-04-20 20:56:58,911] {standard_task_runner.py:98} ERROR - Failed to execute job 759 for task download_dataset_task (Bash command failed. The command returned a non-zero exit code 22.; 2200)
[2022-04-20 20:56:58,924] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-04-20 20:56:58,941] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
